version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery

  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-certs:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    command: certonly --webroot -w /var/www/html -d example.com
    volumes:
      - certbot-certs:/etc/letsencrypt
    networks:
      - my-network
    depends_on:
      - nginx

  celery:
    build: .
    command: celery -A main.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BROKER_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  certbot-certs: