version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=autocodr
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 2s
      retries: 10

  api:
    image: autocodr-api
    build: autocodr
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/healthcheck/ || exit 1 
      interval: 17s
      timeout: 5s
      retries: 3

volumes:
  postgres:
